---
title: "Demographic Analysis"
author: "Simon Hanzal"
date: "11 11 2022"
output: html_document
---
# Setup

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Modify path as needed depending on where the files are stored in your device
# path <- r"(C:\Users\hanza\OneDrive\Dokumenty\R)"
path <- r"(C:\Users\simonha\OneDrive - University of Glasgow\research\data\exp1_data\compilation)"
knitr::opts_knit$set(root.dir = path)
library(tidyverse)
library(readxl)
library(broom)
library(viridis)
library(ez)
library(lme4)
library(lmerTest )
```

```{r load, echo=FALSE}
trial_data <- read_excel("behavioural.xlsx")
excluded = c(
   10004, 10006, 10502, 15004, 15508, 15509 
)
```

# Removals
## Participant level
```{r cleaning, echo=FALSE}
trial_data <- trial_data %>%
    filter(participant < 16000) %>%
    filter(!is.na(participant)) %>%
    # exclusions
    filter(!participant %in% excluded) %>%
    filter(block >= 1.0 & block <= 8.0) %>%
    mutate(age_group = ifelse(participant >= 10600, "older", "young")) %>%
    group_by(participant) %>%
    mutate(observation = 1:n()+1) %>%
    ungroup()

rt_data <- trial_data %>%
    filter(condition == "Go") %>%
    filter(Stimulus.ACC == 1)

nogo_data <- trial_data %>%
    filter(condition == "NoGo")
```

## Trial level

### Behavioural to Neural

```{r}
behavioural_rejections <- rt_data %>%
  group_by(block, age_group) %>%
  mutate(mean_rt = mean(Stimulus.RT), sd_rt = sd(Stimulus.RT)) %>%
  ungroup() %>%
  select(participant, block, stimulus, age_group, observation, Stimulus.RT, mean_rt, sd_rt) %>%
  filter(Stimulus.RT <= mean_rt-2*sd_rt | Stimulus.RT >= mean_rt+2*sd_rt)

behavioural_rejections_specific <- behavioural_rejections %>%
    filter(!participant %in% excluded) %>%
    filter(observation < 91 | observation > 625)

write.csv(behavioural_rejections_specific, "behavioural_rejections.csv")
  
behavioural_rejections_intersect <- behavioural_rejections %>%
    select(participant, observation)

behavioural_rt <- rt_data %>%
    anti_join(behavioural_rejections_intersect)
```



### Neural to Behavioural
```{r}
neural_rejections <- read_excel("data_removal_long_f.xlsx")

neural_rejections_intersect <- neural_rejections %>%
    select(participant, observation)

neural_rt <- behavioural_rt %>%
    inner_join(neural_rejections_intersect)

neural_nogo <- nogo_data %>%
    inner_join(neural_rejections_intersect)

```


# Description

## Assumption check distribution

```{r}
hist(log(neural_rt$Stimulus.RT))
# log_transform necessary
```


## Summaries

```{r rt_sum, echo=FALSE}
rt <- neural_rt %>%
  group_by(block, participant) %>%
  summarise(rt = mean(log(Stimulus.RT)), sd = sd(log(Stimulus.RT)),
            min = min(log(Stimulus.RT)), max = max(log(Stimulus.RT)), trials = n())

rt_natural <- neural_rt %>%
  group_by(block, participant) %>%
  summarise(rt = mean(Stimulus.RT), sd = sd(Stimulus.RT),
            min = min(Stimulus.RT), max = max(Stimulus.RT), trials = n()) %>%
  mutate(age_group = ifelse(participant >= 10600, "older", "young"))
  

# calculate change score
rt_change <-  rt %>%
  filter(block == 1 | block == 8) %>%
  select(participant, block, rt) %>%
  pivot_wider(names_from = block, values_from = rt) %>%
  mutate(rt_change = `8` - `1`) %>%
  select(participant, rt_change)

rt_overall <- rt %>%
  ungroup() %>%
  group_by(participant) %>%
  summarise(rt_overall = mean(rt))

rt_anova <- rt %>%
      mutate(age_group = ifelse(participant >= 10600, "older", "young")) %>%
    filter(block == 1 | block == 8) %>%
    mutate(age_group = recode(age_group, "young" = 0, "older" = 1)) %>%
    mutate(block = recode(block, "1" = 0, "8" = 1))
  
# calculate accuracy score more cleverly
err <- nogo_data %>%
  group_by(participant, block) %>%
  count(Stimulus.ACC) %>%
  mutate(block_total = sum(n)) %>%
  filter(Stimulus.ACC == 1) %>%
  mutate(err = (1 - (n/block_total) ) * 100)

err_summary <- err %>%
  mutate(age_group = ifelse(participant >= 10600, "older", "young")) %>%
  group_by(block, age_group) %>%
    summarise(mean = mean(err), sd = sd(err),
            min = min(err), max = max(err), trials = n())

err_change <- err %>%
  filter(block == 1 | block == 8) %>%
  select(participant, block, err) %>%
  pivot_wider(names_from = block, values_from = err) %>%
  mutate(err_change = `8` - `1`) %>%
  select(participant, err_change)

err_overall <- err %>%
  ungroup() %>%
  group_by(participant) %>%
  summarise(err_overall = mean(err))

err_anova <- err %>%
      mutate(age_group = ifelse(participant >= 10600, "older", "young")) %>%
    filter(block == 1 | block == 8) %>%
    mutate(age_group = recode(age_group, "young" = 0, "older" = 1)) %>%
    mutate(block = recode(block, "1" = 0, "8" = 1))
  

# calculate accuracy change

# assemble

# has age, vas_change, err_change, rt_change, mean_rt, mean_err and space for alpha_change
vas_change <- read_csv("subjective_difference.csv") %>%
  mutate(participant = ID, vas_change = subjective_difference) %>%
  select(participant, vas_change)

all_data <- inner_join(
  inner_join(
  rt_change, rt_overall, by="participant"
  ),
  inner_join(
  err_change, err_overall, by="participant"
  ), by="participant"
) %>%
  inner_join(vas_change, by="participant") %>%
  mutate(age_group = ifelse(participant >= 10600, 1, 0))
```

# Modelling

## Confirmation t-test for changes
```{r}
# rt change
rt_test <-rt %>%
  filter(block == 1 | block == 8) %>%
  select(participant, block, rt) %>%
  pivot_wider(names_from = block, values_from = rt)

rt_test <- t.test(rt_test$`1`, rt_test$`8`, paired = TRUE)
tidy(rt_test)
# error change
err_test <- err %>%
  filter(block == 1 | block == 8) %>%
  select(participant, block, err) %>%
  pivot_wider(names_from = block, values_from = err)

err_test <- t.test(err_test$`1`, err_test$`8`, paired = TRUE)
tidy(err_test)
```


## Main models
```{r}
# error

# Think about the interactions
error_model <- lm(
err_overall ~ age_group + vas_change + rt_overall + rt_change + err_change,
all_data
)
summary(error_model)

error_change_model <- lm(
err_change ~ age_group + vas_change + rt_overall + rt_change + err_overall,
all_data
)
summary(error_change_model)
```

```{r}
neural_data <- read_xlsx("neural_summary.xlsx") %>%
    inner_join(all_data, by="participant")

neural_data <- neural_data %>%
    mutate(block_change_beta = last_beta-first_beta, block_change_alpha = last_alpha - first_alpha)
# Look for brain and behaviour link

wan_addition <- demo_clean_wan %>%
    pivot_wider(names_from ="timepoint", values_from = "wan") %>%
    mutate(wan_change = `1` - `0`, participant = ID) %>%
    select(participant, wan_change)
neural_data <- neural_data %>%
    inner_join(wan_addition, "participant")

model <- lm(err_change ~ block_change_beta*age_group, neural_data)
summary(model)

model <- lm(err_change ~ block_change_alpha, neural_data)
summary(model)

model <- lm(wan_change ~ block_change_alpha*age_group, neural_data)
summary(model)

model <- lm(wan_change ~ block_change_beta*age_group, neural_data)
summary(model)

neural_data_long_alpha <- neural_data %>%
    pivot_longer(first_alpha:last_alpha, "block","value")

neural_data_long_beta <- neural_data %>%
    pivot_longer(first_beta:last_beta, "block","value")

model <- lm(value ~ block, neural_data_long_alpha)
summary(model)

model <- lm(value ~ block, neural_data_long_beta)
summary(model)


model <- lm(block_change_alpha ~ block_change_beta, neural_data_long_beta)
summary(model)

```

```{r}
model <- t.test(all_data$age_group, all_data$err_overall, within = FALSE, anternative = "greater")
tidy(model)

# err_anova <- err_anova %>%
#     filter(participant > 10001)

model <- ezANOVA(
	err_anova
	, dv = err
	, wid = participant
	, within = as.factor(block)
	, between = as.factor(age_group)

)
model


model <- lmer(err ~ block * age_group + (1 | participant), err_anova)
summary(model)
anova(model)

model <- lmer(rt ~ block * age_group + (1 | participant), rt_anova)
summary(model)
anova(model)

model <- lm(rt_overall ~ err_overall*age_group, all_data)
summary(model)

vas_anova <- demo_clean_lm %>%
    mutate(age_group = ifelse(ID >= 10600, 1, 0))

wan_anova <- demo_clean_wan %>%
    mutate(age_group = ifelse(ID >= 10600, 1, 0))

comparison <- lm(vas ~ timepoint * age_group, vas_anova)
summary(model)

model <- lmer(vas ~ timepoint * age_group + (1 | ID), vas_anova)
summary(model)
#anova(model,comparison)

model <- lmer(wan ~ timepoint * age_group + (1 | ID), wan_anova)
summary(model)
```


# Plotting

```{r}
plot_nogo_young <- ggplot(filter(err, participant <= 10600), aes(x = as.factor(block), y = as.numeric(err), fill = as.factor(block))) +
  geom_violin(alpha = 0.4, adjust  = 0.6) +
  geom_point(aes(colour = as.factor(participant)),shape = 4, alpha = 0.5) +
  geom_line(aes(colour = as.factor(participant)), group= 1, alpha = 0.5) +
  stat_summary(fun.y="median") +
  ggtitle("Young - Commission Error") +
  xlab("Block") +
  ylab("Commission Error") +
  theme_minimal() +
  scale_color_viridis(discrete = TRUE, option = "D") +
  scale_fill_viridis_d(limits=rev, option = "D", begin = 0.4, end = 0.8) +
  scale_y_continuous(limits = c(0, 100)) +
  theme(legend.position = 0, text=element_text(size=18,  family="Times New Roman"), axis.text=element_text(size=16))

plot_nogo_older <- ggplot(filter(err, participant >= 10600), aes(x = as.factor(block), y = as.numeric(err), fill = as.factor(block))) +
  geom_violin(alpha = 0.4, adjust  = 3) +
  geom_point(aes(colour = as.factor(participant)),shape = 4, alpha = 0.5) +
  geom_line(aes(colour = as.factor(participant)), group= 1, alpha = 0.5) +
  stat_summary(fun.y="median") +
  ggtitle("Older - Commission Error") +
  xlab("Block") +
  ylab("Commission Error") +
  theme_minimal() +
  scale_color_viridis(discrete = TRUE, option = "D") +
  scale_fill_viridis_d(limits=rev, option = "D", begin = 0.4, end = 0.8) +
  scale_y_continuous(limits = c(0, 100)) +
  theme(legend.position = 0, text=element_text(size=18,  family="Times New Roman"), axis.text=element_text(size=16))

plot_nogo_young
plot_nogo_older
# path = r"(C:\Users\hanza\OneDrive\Dokumenty\R\plots)"
path <- r"(C:\Users\simonha\OneDrive - University of Glasgow\research\data\exp1_data\compilation\newer_plots)"
ggsave(plot_nogo_young, filename = 'nogo_young.png', path = path, dpi = 1200, type = 'cairo', width = 10, height = 4.5, units = 'in', bg = 'white')
ggsave(plot_nogo_older, filename = 'nogo_older.png', path = path, dpi = 1200, type = 'cairo', width = 10, height = 4.5, units = 'in', bg = 'white')

```

```{r}
plot_rt_young <- ggplot(filter(rt_natural, age_group=="young"), aes(x = as.factor(block), y = as.numeric(rt), fill = as.factor(block))) +
  geom_violin(alpha = 0.4, adjust  = 0.8) +
  geom_point(aes(colour = as.factor(participant)),shape = 4, alpha = 0.5) +
  geom_line(aes(colour = as.factor(participant)), group= 1, alpha = 0.5) +
  geom_boxplot(alpha = 0.2, varwidth = TRUE, width = 0.45, outlier.shape = NA, coef = 0) +
  ggtitle("Young - Reaction Time change") +
  xlab("Block") +
  ylab("Reaction Time (ms)") +
  theme_minimal() +
  scale_color_viridis(discrete = TRUE, option = "D") +
  scale_y_continuous(limits = c(250, 1000)) +
  scale_fill_viridis_d(limits=rev, option = "D", begin = 0.4, end = 0.8) +
  theme(legend.position = 0, text=element_text(size=18,  family="Times New Roman"), axis.text=element_text(size=16))

plot_rt_older <- ggplot(filter(rt_natural, age_group=="older"), aes(x = as.factor(block), y = as.numeric(rt), fill = as.factor(block))) +
  geom_violin(alpha = 0.4, adjust  = 0.8) +
  geom_point(aes(colour = as.factor(participant)),shape = 4, alpha = 0.5) +
  geom_line(aes(colour = as.factor(participant)), group= 1, alpha = 0.5) +
  geom_boxplot(alpha = 0.2, varwidth = TRUE, width = 0.45, outlier.shape = NA, coef = 0) +
  ggtitle("Older - Reaction Time change") +
  xlab("Block") +
  ylab("Reaction Time (ms)") +
  theme_minimal() +
  scale_color_viridis(discrete = TRUE, option = "D") +
  scale_y_continuous(limits = c(250, 1000)) +
  scale_fill_viridis_d(limits=rev, option = "D", begin = 0.4, end = 0.8) +
  theme(legend.position = 0, text=element_text(size=18,  family="Times New Roman"), axis.text=element_text(size=16))

plot_rt_young
plot_rt_older
ggsave(plot_rt_young, filename = 'rt_young.png', path = path, dpi = 1200, type = 'cairo', width = 10, height = 4.5, units = 'in', bg = 'white')
ggsave(plot_rt_older, filename = 'rt_older.png', path = path, dpi = 1200, type = 'cairo', width = 10, height = 4.5, units = 'in', bg = 'white')
```

```{r}
model <- lm(err_change ~ block_change_alpha, neural_data)
summary(model)

hist(neural_data$err_change)

hist(neural_data$block_change_alpha)

plot_brain_behaviour <- ggplot(neural_data, aes(block_change_alpha, err_change)) +
    geom_point() +
    geom_smooth(method = "lm", se = FALSE)

plot_brain_behaviour

plot_trade_off <- ggplot(all_data, aes(rt_change, err_change)) +
    geom_point() +
    geom_smooth(method = "lm", se = FALSE)

plot_trade_off

model <- lm(value ~ block, filter(neural_data_long_beta, participant <= 10600))
summary(model)
```

```{r}
plot_alpha_young <- ggplot(filter(neural_data_long_alpha, participant <= 10600), aes(x = as.factor(block), y = as.numeric(value), fill = as.factor(block))) +
  geom_violin(alpha = 0.4, adjust  = 0.8) +
  geom_point(aes(colour = as.factor(participant)),shape = 4, alpha = 0.5) +
  geom_line(aes(colour = as.factor(participant)), group= 1, alpha = 0.5) +
  geom_boxplot(alpha = 0.2, varwidth = TRUE, width = 0.45, outlier.shape = NA, coef = 0) +
  ggtitle("Young - Alpha change") +
  xlab("Time") +
  ylab("Total Score") +
  theme_minimal() +
  scale_color_viridis(discrete = TRUE, option = "C") +
  scale_fill_viridis_d(option = "C", begin = 0, end = 1) +
  #scale_x_discrete(labels=c("1" = "First Block", "0" = "Last block"), limits=rev) +
  ylim(0,3) +
  theme(legend.position = 0, text=element_text(size=18,  family="Times New Roman"), axis.text=element_text(size=16))

plot_alpha_older <- ggplot(filter(neural_data_long_alpha, participant >= 10600), aes(x = as.factor(block), y = as.numeric(value), fill = as.factor(block))) +
  geom_violin(alpha = 0.4, adjust  = 0.8) +
  geom_point(aes(colour = as.factor(participant)),shape = 4, alpha = 0.5) +
  geom_line(aes(colour = as.factor(participant)), group= 1, alpha = 0.5) +
  geom_boxplot(alpha = 0.2, varwidth = TRUE, width = 0.45, outlier.shape = NA, coef = 0) +
  ggtitle("Older - Alpha change") +
  xlab("Time") +
  ylab("Total Score") +
  theme_minimal() +
  scale_color_viridis(discrete = TRUE, option = "C") +
  scale_fill_viridis_d(option = "C", begin = 0, end = 1) +
  #scale_x_discrete(labels=c("1" = "First Block", "0" = "Last block"), limits=rev) +
  ylim(0,3) +
  theme(legend.position = 0, text=element_text(size=18,  family="Times New Roman"), axis.text=element_text(size=16))


plot_alpha_young
plot_alpha_older
#path = r"(C:\Users\hanza\OneDrive\Dokumenty\R\plots)"
path <- r"(C:\Users\simonha\OneDrive - University of Glasgow\research\data\exp1_data\compilation)"
ggsave(plot_alpha_young, filename = 'alpha_young.png', path = path, dpi = 1200, type = 'cairo', width = 10, height = 4.5, units = 'in', bg = 'white')
ggsave(plot_alpha_older, filename = 'alpha_older.png', path = path, dpi = 1200, type = 'cairo', width = 10, height = 4.5, units = 'in', bg = 'white')

```

```{r}
plot_beta_young <- ggplot(filter(neural_data_long_beta, participant <= 10600), aes(x = as.factor(block), y = as.numeric(value), fill = as.factor(block))) +
  geom_violin(alpha = 0.4, adjust  = 0.8) +
  geom_point(aes(colour = as.factor(participant)),shape = 4, alpha = 0.5) +
  geom_line(aes(colour = as.factor(participant)), group= 1, alpha = 0.5) +
  geom_boxplot(alpha = 0.2, varwidth = TRUE, width = 0.45, outlier.shape = NA, coef = 0) +
  ggtitle("Young - Beta change") +
  xlab("Time") +
  ylab("Total Score") +
  theme_minimal() +
  scale_color_viridis(discrete = TRUE, option = "E") +
  scale_fill_viridis_d(option = "E", begin = 0, end = 1) +
  #scale_x_discrete(labels=c("1" = "First Block", "0" = "Last block"), limits=rev) +
  ylim(0,3) +
  theme(legend.position = 0, text=element_text(size=18,  family="Times New Roman"), axis.text=element_text(size=16))

plot_beta_older <- ggplot(filter(neural_data_long_beta, participant >= 10600), aes(x = as.factor(block), y = as.numeric(value), fill = as.factor(block))) +
  geom_violin(alpha = 0.4, adjust  = 0.8) +
  geom_point(aes(colour = as.factor(participant)),shape = 4, alpha = 0.5) +
  geom_line(aes(colour = as.factor(participant)), group= 1, alpha = 0.5) +
  geom_boxplot(alpha = 0.2, varwidth = TRUE, width = 0.45, outlier.shape = NA, coef = 0) +
  ggtitle("Older - Beta change") +
  xlab("Time") +
  ylab("Total Score") +
  theme_minimal() +
  scale_color_viridis(discrete = TRUE, option = "E") +
  scale_fill_viridis_d(option = "E", begin = 0, end = 1) +
  #scale_x_discrete(labels=c("1" = "First Block", "0" = "Last block"), limits=rev) +
  ylim(0,3) +
  theme(legend.position = 0, text=element_text(size=18,  family="Times New Roman"), axis.text=element_text(size=16))


plot_beta_young
plot_beta_older
#path = r"(C:\Users\hanza\OneDrive\Dokumenty\R\plots)"
path <- r"(C:\Users\simonha\OneDrive - University of Glasgow\research\data\exp1_data\compilation)"
ggsave(plot_beta_young, filename = 'newer_plots/beta_young.png', path = path, dpi = 1200, type = 'cairo', width = 10, height = 4.5, units = 'in', bg = 'white')
ggsave(plot_beta_older, filename = 'newer_plots/beta_older.png', path = path, dpi = 1200, type = 'cairo', width = 10, height = 4.5, units = 'in', bg = 'white')

```
