---
title: "Demographic Analysis"
author: "Simon Hanzal"
date: "11 11 2022"
output: html_document
---
# Setup

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Modify path as needed depending on where the files are stored in your device
path <- r"(C:\Users\hanza\OneDrive\Dokumenty\R)"
# path <- r"(C:\Users\simonha\OneDrive - University of Glasgow\research\data\exp1_data\compilation)"
knitr::opts_knit$set(root.dir = path)
library(tidyverse)
library(readxl)
library(broom)
library(lme4)
```

```{r load, echo=FALSE}
demographic_data <- read_excel("demographic.xlsx")
excluded = c(
    10004, 10006, 10502, 15004, 15508, 15509
)
```


```{r cleaning, echo=FALSE}
demo_clean <- demographic_data %>%
    filter(!is.na(ID)) %>%
    # exclusions
    filter(!ID %in% excluded) %>%
    mutate(age_group = ifelse(age <= 50, "young", "older"))
```

# Description

## Age description 80

``` {r age, echo=FALSE}
age_information <- demo_clean %>%
    group_by(age_group) %>%
    summarise(mean = mean(age), sd = sd(age), median = median(age), min = min(age), max = max(age), number = n())
```

## vas description 80

```{r vas, echo=FALSE}
prevas_information <- demo_clean %>%
    group_by(age_group) %>%
    summarise(mean = mean(`pre-vas`), sd = sd(`pre-vas`), median = median(`pre-vas`), min = min(`pre-vas`), max = max(`pre-vas`), number = n())
prevas_information

postvas_information <- demo_clean %>%
    group_by(age_group) %>%
    summarise(mean = mean(`post-vas`), sd = sd(`post-vas`), median = median(`pre-vas`), min = min(`post-vas`), max = max(`post-vas`), number = n())
postvas_information

vaschange_information <- demo_clean %>%
    group_by(age_group) %>%
    summarise(mean = mean(`dif-vas`), sd = sd(`dif-vas`), median = median(`dif-vas`), min = min(`dif-vas`), max = max(`dif-vas`), number = n())
vaschange_information
```

## vas test 95
```{r}
main_test <- t.test(demo_clean$`pre-vas`, demo_clean$`post-vas`, paired = TRUE)
tidy(main_test)

demo_clean_lm <- demo_clean %>%
    pivot_longer(c(`pre-vas`, `post-vas`), names_to = "timepoint", values_to = "vas") %>%
    mutate(timepoint = recode(timepoint, "pre-vas" = 1, "post-vas" = 0)) %>%
    select(ID, timepoint, vas)

main_test_test <- lmer(timepoint ~ vas + (1 | ID), demo_clean_lm)
summary(main_test_test)
main_test_test

library(afex)
mod <- mixed(timepoint ~ vas + (1 | ID), type=3,method="KR",data=demo_clean_lm) 
mod
```

## vas export 90

```{r}
demo_export <- demo_clean %>%
    mutate(subjective_difference = `dif-vas`) %>%
    select(ID, subjective_difference)

write.csv(demo_export, "subjective_difference.csv")
```


## vas plot 10
Bring from elsewhere

```{r}
plot_vas_young <- ggplot(filter(demo_clean_lm, ID <= 10600), aes(x = as.factor(timepoint), y = as.numeric(vas), fill = as.factor(timepoint))) +
  geom_violin(alpha = 0.4, adjust  = 0.8) +
  geom_point(aes(colour = as.factor(ID)),shape = 4, alpha = 0.5) +
  geom_line(aes(colour = as.factor(ID)), group= 1, alpha = 0.5) +
  geom_boxplot(alpha = 0.2, varwidth = TRUE, width = 0.45, outlier.shape = NA, coef = 0) +
  ggtitle("Young - Subjective Fatigue change") +
  xlab("Time") +
  ylab("Total Score") +
  theme_minimal() +
  scale_color_viridis(discrete = TRUE, option = "D") +
  scale_fill_viridis_d(option = "D", begin = 0, end = 1) +
  scale_x_discrete(labels=c("1" = "Pre-task", "0" = "Post-task"), limits=rev) +
  theme(legend.position = 0, text=element_text(size=18,  family="Times New Roman"), axis.text=element_text(size=16))

plot_vas_older <- ggplot(filter(demo_clean_lm, ID >= 10600), aes(x = as.factor(timepoint), y = as.numeric(vas), fill = as.factor(timepoint))) +
  geom_violin(alpha = 0.4, adjust  = 0.8) +
  geom_point(aes(colour = as.factor(ID)),shape = 4, alpha = 0.5) +
  geom_line(aes(colour = as.factor(ID)), group= 1, alpha = 0.5) +
  geom_boxplot(alpha = 0.2, varwidth = TRUE, width = 0.45, outlier.shape = NA, coef = 0) +
  ggtitle("Older - Subjective Fatigue change") +
  xlab("Time") +
  ylab("Total Score") +
  theme_minimal() +
  scale_color_viridis(discrete = TRUE, option = "D") +
  scale_fill_viridis_d(option = "D", begin = 0, end = 1) +
  scale_x_discrete(labels=c("1" = "Pre-task", "0" = "Post-task"), limits=rev) +
  theme(legend.position = 0, text=element_text(size=18,  family="Times New Roman"), axis.text=element_text(size=16))


plot_vas_young
plot_vas_older
path = r"(C:\Users\hanza\OneDrive\Dokumenty\R\plots)"
ggsave(plot_vas_young, filename = 'vas_young.png', path = path, dpi = 1200, type = 'cairo', width = 10, height = 4.5, units = 'in', bg = 'white')
ggsave(plot_vas_older, filename = 'vas_older.png', path = path, dpi = 1200, type = 'cairo', width = 10, height = 4.5, units = 'in', bg = 'white')

```

